language : java

sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "mckratt-github"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin repo.treescale.com

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Ddocker.image.prefix=repo.treescale.com/bakaar
