language : java

sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "mckratt-github"

script:
#Log in to docker registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./travis-build.sh