language : java

sudo: required

services:
  - docker

addons:
  sonarcloud:
    organization: "mckratt-github"

script:
#Log in to docker registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
