version: '3'
services:
  business-number-service:
    container_name: "businessnumber"
    image: bakaar/businessnumber:latest
    ports:
      - 8080
  person-db:
    container_name: "person-db"
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: person_user
    ports:
      - "5432:5432"
