version: '3'
services:
  case-db:
    container_name: "case-db"
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: case_user
    ports:
      - "5432:5432"
  case-service:
    container_name: "case-service"
    image: sandbox/case-application:BETA
    ports:
      - "9080:8080"
    environment:
      case.db.url: jdbc:postgresql://db:5432/case_user
      case.db.user: case_user
      case.db.pass: 123456
      case.db.driver: org.postgresql.Driver
    links:
      - case-db:db